# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gnFK6ZR9j-HDsZS0KSj3Q_zIRGLvDfsd
"""

import random
n=5000
colour={0,1,2,3}  #0=black, 1=blue, 2=green, 3=red
same_colour=0
for i in range(n):
    x=random.randint(0,3)   #colour on Pen 1
    y=random.randint(0,3)   #colour on Pen 2
    z=random.randint(0,3)   #colour on Pen 3
    if x==y and y==z :
        same_colour+=1
print(f"The probability that the candidate comes with all 3 pens of same colour, as Predicted by SIMULATION is {same_colour/n}")